name: CI
on:
  push:
  pull_request:

jobs:
  build:
    timeout-minutes: 2
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - run: pip install jupyter-nbconvert
    - run: bash scripts/build.sh
